import { NextResponse } from 'next/server';

export const dynamic = 'force-dynamic';
export const maxDuration = 300;

const BASE = 'https://www.cha-lab.com';
const PUBLIC_PROFILE = `27세. 말수가 적지만 가까운 사람 앞에서는 장난이 많다.
약속 시간은 거의 어기지 않고, 다른 사람이 늦는 건 한두 번은 넘어가지만 반복되면 이유를 직접 묻는다.
동생이 곤란한 일을 겪으면 먼저 해결책을 찾지만 본인이 힘들 때는 도움을 잘 요청하지 않는다.
게임이나 승부에서는 지는 걸 싫어하지만 상대가 실수해서 이기는 건 찝찝해한다.
여행을 다녀오면 표, 영수증, 작은 안내지를 모아 상자에 보관한다.
사람이 많은 장소에서는 오래 있으면 지치며, 혼자 걷거나 조용한 카페에서 쉬는 걸 좋아한다.
누군가 부당하게 대우받는 걸 보면 모른 척하지 못하고 상황을 확인한 뒤 필요한 말을 한다.
화가 났을 때 바로 소리치기보다 말을 줄이고 혼자 정리한 다음 다시 대화하는 편이다.
사과할 때 긴 설명보다 잘못한 부분을 고치거나 다음 행동으로 보여주는 쪽을 편하게 느낀다.
친하지 않은 사람이 사적인 질문을 계속하면 웃으며 넘기다가 선을 긋는다.
일을 맡으면 끝까지 책임지려 하지만, 계획이 틀어지면 혼자서라도 원래 수준을 맞추려고 무리하는 경향이 있다.`;
const SECRET_PROFILE = `가족의 경제 사정이 좋지 않았던 시기가 길어서 돈이나 빚 이야기에 예민하다.
본인이 누군가에게 부담이 되는 상황을 특히 싫어해 부탁을 미루는 편이다.
친한 사람에게 실망했을 때 관계를 바로 끊기보다 한 번은 이유를 확인하지만, 같은 문제가 반복되면 조용히 거리를 둔다.
어릴 때부터 모아온 여행 표와 영수증 중 일부는 힘들었던 시기의 기억과 연결되어 있어 버리지 못한다.`;
const sleep=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms));
async function post(path:string,body:unknown,attempts=5){let last='';for(let attempt=1;attempt<=attempts;attempt+=1){const response=await fetch(`${BASE}${path}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body),cache:'no-store'});const text=await response.text();last=`${response.status}: ${text.slice(0,1200)}`;if(response.ok)return text;if(response.status<500)throw new Error(`${path} ${last}`);await sleep(1000*attempt);}throw new Error(`${path} failed after retries: ${last}`);}
function streamResult(text:string){const lines=text.trim().split(/\n+/).map(line=>JSON.parse(line));const error=lines.find(item=>item.error);if(error)throw new Error(JSON.stringify(error));const last=[...lines].reverse().find(item=>item.result);if(!last)throw new Error('missing stream result');return last.result;}
function makeAnswer(q:Record<string,any>,order:number){const c=q.responseConfig||{},o:string[]=q.options||[];const pick=(a:string[]|undefined,i=0)=>a?.length?a[Math.min(i,a.length-1)]:'';let answer='',answerSource='structured';switch(q.responseType){case'fill_blank':case'dialogue_choice':case'owner_meta':case'forced_choice':answer=pick(o,order%Math.max(1,o.length));answerSource='choice';break;case'sentence_continue':case'in_character_response':answer=['일단 내가 할 수 있는 데까지 해본다.','말로 설명하기 전에 상황을 먼저 정리한다.','가까운 사람에게는 이유를 확인하고 한 번 더 기회를 준다.'][order%3];answerSource='custom';break;case'bipolar_scale':answer=`${c.leftLabel||'A'} 60% / ${c.rightLabel||'B'} 40%`;break;case'ranking':answer=o.map((x,i)=>`${i+1}위 ${x}`).join(' > ');break;case'multi_select':answer=`복수 선택: ${o.slice(0,2).join(', ')}`;break;case'least_likely':answer=`가장 하지 않을 것: ${pick(o)}`;answerSource='choice';break;case'slider':answer=`65/100 (${c.minLabel||'낮음'} ↔ ${c.maxLabel||'높음'})`;break;case'relationship_matrix':answer=(c.rows||[]).map((row:string)=>`${row}: ${pick((c.rowOptions||{})[row]||c.columns||[])}`).join(' / ');break;case'inner_outer':answer='속마음: 내가 먼저 정리해야 한다고 생각한다 / 실제 행동: 바로 말하지 않고 필요한 행동부터 한다';answerSource='custom';break;case'temporal_compare':answer=`${c.leftLabel||'처음'}: ${pick(o)} / ${c.rightLabel||'나중'}: ${pick(c.options2||[])}`;break;case'condition_followup':answer=`기본 상황: ${pick(o)} / 조건 변경 후: ${pick(c.options2||[])}`;break;default:answer=pick(o)||'상황을 먼저 확인한 뒤 판단한다.';}if(!answer.trim())answer='상황을 먼저 확인한 뒤 판단한다.';const reasons=['이 답이 기본값에 가장 가깝지만 가까운 사람에게는 예외가 생길 수 있다.','감정보다 내가 지켜야 할 기준을 먼저 생각하는 편이라서다.','바로 반응하기보다 상황을 확인한 뒤 행동하는 쪽이 더 자연스럽다.','상대와의 거리와 책임이 걸린 정도에 따라 반응이 조금 달라진다.'];return{order:q.order,question:q.question,answer,reason:reasons[(order-1)%4],branchContext:{category:q.category,mode:q.mode,format:q.format,responseType:q.responseType,targetHook:q.targetHook,hypothesis:q.hypothesis,answerSource}};}
export async function GET(){try{const parsed=streamResult(await post('/api/characters/parse',{name:'테스트 캐릭터 윤서',profileText:PUBLIC_PROFILE,secretProfileText:SECRET_PROFILE,appearanceImages:[]}));const draft=parsed.draft;draft.aiInferences=(draft.aiInferences||[]).map((item:Record<string,unknown>)=>({...item,ownerVerdict:'confirmed'}));const answers:unknown[]=[],questions:Record<string,any>[]=[];for(let order=1;order<=20;order+=1){const raw=await post('/api/characters/questions/next',{draft,answers,plannedQuestions:[],startOrder:order,batchSize:1});const body=JSON.parse(raw);const q=body.question||body.questions?.[0];if(!q)throw new Error(`missing Q${order}`);questions.push(q);answers.push(makeAnswer(q,order));}const categoryCounts:Record<string,number>={},modeCounts:Record<string,number>={};for(const q of questions){categoryCounts[q.category]=(categoryCounts[q.category]||0)+1;modeCounts[q.mode]=(modeCounts[q.mode]||0)+1;}const exactHookRepeats=questions.length-new Set(questions.map(q=>String(q.targetHook).trim().toLowerCase())).size;let longestNonPivot=0,run=0;for(const q of questions){run=q.mode==='pivot'?0:run+1;longestNonPivot=Math.max(longestNonPivot,run);}return NextResponse.json({categoryCounts,modeCounts,exactHookRepeats,longestNonPivot,questions:questions.map(q=>({order:q.order,category:q.category,mode:q.mode,targetHook:q.targetHook,question:q.question,responseType:q.responseType}))});}catch(error){return NextResponse.json({error:error instanceof Error?error.message:String(error)},{status:500});}}
